config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 20}
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">Simple Airbnb</a>
  <form class="form-inline">
    <button class="btn btn-outline-primary" type="button">
      <%= link_to "Add Flat", new_flat_path %>
    </button>
  </form>
</div>

<div class="container">
  <div class="flats-list">
  <h1><strong><%= "All our flats (#{@flats.count})" %></strong></h1>
  <div class="cards d-flex row">
    <% @flats.each do |flat| %>
      <div class="card" style="width: 400px;">
        <div class="card-content card-header">
          <h5><strong><%= flat.name %></strong></h5>
          <p><%= flat.address %></p>
          <p><i class="fal fa-user-friends"></i> <%= flat.number_of_guests %></p>
          <p><i class="fal fa-pound-sign"></i> <%= flat.price_per_night %></p>
        </div>
        <div class="card-actions">
          <%= link_to "More info", flat_path(flat) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Create flat", class: "btn btn-primary" %>
    <%= f.button :button, "Cancel", class: "btn btn-danger" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">Simple Airbnb</a>
  <form class="form-inline">
    <button class="btn btn-outline-primary" type="button">
      <%= link_to "Add Flat", new_flat_path %>
    </button>
  </form>
</div>

<div class="container">
  <div class="container flat">
    <div class="container flat-title">
      <h2><%= @flat.name %></h2>
      <h5><%= @flat.address %></h5>
    </div>

    <div class="container flat-description">
      <h3>A bit more about this flat...</h3>
      <p><%= @flat.description %></p>
    </div>
  </div>

  <div class="container other">
    <div class="container booking">
      <h4>Book this place!</h4>
    </div>
    <div class="container details">
      <h4>Details</h4>
      <p><i class="fal fa-user-friends"></i> <%= @flat.number_of_guests %></p>
      <p><i class="fal fa-pound-sign"></i> <%= @flat.price_per_night %></p>
    </div>
    <div class="container socila-media">
      <h5>Share</h5>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="../../assets/stylesheets/application.scss" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  </head>

  <body style="background-color:white;">
    <%= yield %>
  </body>
</html>